classdef (Abstract) RetCell < squirrellab.sources.Cell
    
    methods
        
        function obj = RetCell()
            import symphonyui.core.*;
            
            obj.addProperty('type', 'photoreceptor', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'', 'photoreceptor', 'horizontal', 'bipolar', 'amacrine', 'RGC', 'other', 'unknown'}, ...
                    { ...
                        {}, ...
                        {'S-cone', 'M-cone', 'L-cone', 'UV-cone', 'cone', 'rod'}, ...
                        {'H1', 'H2'}, ...
                        {'rbc', 'cbc', 'on-cbc', 'off-cbc'}, ...
                        {'AII', 'A17', 'starburst', 'AC5170', 'vGlut3'}, ...
                        {'ipRGC','ON-alpha', 'ON-transient', 'OFF-transient', 'OFF-sustained', 'ON/OFF DS', 'ON DS', 'W3/local edge detector'}, ...
                        {}, ...
                        {}, ...
                    })), ...
                'description', 'The confirmed type of the recorded cell', ...
                'isPreferred', true);   
    end
    
    end
end
