classdef (Abstract) EpochGroup < symphonyui.core.persistent.descriptions.EpochGroupDescription
    
    methods
        
        function obj = EpochGroup()
            import symphonyui.core.*;
            
            obj.addProperty('externalSolutionAdditions', {}, ...
                'type', PropertyType('cellstr', 'row', {...
                'SR101 (1 uM)',...
                'SR101 (500 nM)',...
                'ZD7288 (100 uM)',...
                'Ivabradine (30 uM)',...
                'BaCl2 (5 mM)',...
                'CoCl2 (5 mM)',...
                'CdCl2 (5 mM)',...
                'NBQX (10uM)',...
                'L-AP4 (20uM)',...
                'GYKI53655 (100uM)',...
                'ACET (1 uM)' ,...
                'DAPV (50uM)',...
                'APB (10uM)',...
                'LY 341495 (10uM)',...
                'strychnine (0.5uM)',...
                'strychnine (25uM)',...
                'gabazine (10uM)',...
                'gabazine (25uM)',...
                'TPMPA (50uM)',...
                'TTX (100nM)',...
                'TTX (500nM)',...
                }));
            obj.addProperty('pipetteSolution', '', ...
                'type', PropertyType('char', 'row', {...
                '',...
                'KAsp 0Ca2+',...
                'CsMs0Ca2+',...
                'CsMs',...
                'KAsp',...
                'KGluc(Shan)',...
                'CsCl',...
                'Ames',...
                'Ringer',...
                'HibA',...
                }));
            obj.addProperty('internalSolutionAdditions', {}, ...
                'type', PropertyType('cellstr', 'row', {...
                'Alexa488',...
                'SR101 (1 uM)',...
                'SR101 (500 nM)',...
                '8Br-cGMP (200 uM)',...
                }));
            obj.addProperty('pufferSolution','', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'', 'IBMX','Ivabradine', 'ZD7288', 'Ca2+'}, ...
                    { ...
                        {}, ...
                        {}, ...
                        {'30uM', '60uM'}, ...
                        {'100uM','200uM'}, ...
                        {'0mM','20uM'}, ...
                    })));
            obj.addProperty('recordingTechnique', '', ...
                'type', PropertyType('char', 'row', {'', 'cell-attached', 'whole-cell', 'perforated patch', 'suction'}));
            obj.addProperty('seriesResistanceCompensation', int32(0), ...
                'type', PropertyType('int32', 'scalar', [0 100]));
            obj.addProperty('lowPassFilter', '2kHz', ...
                'type', PropertyType('char', 'row', {'1kHz', '2kHz', '5kHz', '10kHz', '100kHz', }));
        end
        
    end
    
end

